### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [is541-sibsutis/coder-simulator#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:

1. В [wiki](https://github.com/is541-sibsutis/coder-simulator/wiki) проекта написана статья с ТЗ.
1. В [issues](https://github.com/is541-sibsutis/coder-simulator/issues) созданы задачи.
1. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by fks213** [comment]
Создали статью на Wiki. Извините, что поздно

**Comment by evgeny-p** [comment]
Заведите задачи.

**Comment by fks213** [comment]
Сделано.

**Comment by evgeny-p** [comment]
Принято. Во многом за активную деятельность и демонстрацию промежуточных наработок.

В случае возникновения аналогичной ситуации в последующих итерациях при прочих равных может быть принято обратное решение.
