### ISSUE TITLE
Список "Компьютер"

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#10]

**Comment by fks213** [comment]
Счеты, Калькулятор, ЭВМ, Pentium 2  ОЗУ 64  GeForce 2, Celeron 2x2,1Ghz ОЗУ 512 GeForce 6600, i3 ОЗУ 2Gb GeForce 650, i7 ОЗУ 8Gb GeForce 860, Xeon ОЗУ 16Gb GeForce 980ti

**Comment by Nemec25** [comment]
Изменение, итоговый список таков: 
Калькулятор
Commodore 64
Celeron 2x2,1Ghz ОЗУ 512 GeForce 6600
i3 ОЗУ 2Gb GeForce 650
Xeon ОЗУ 16Gb GeForce 980ti
