### ISSUE TITLE
Список "Знания"

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#12]

**Comment by fks213** [comment]
Прочитать учебник, Курсы, Олимпиада, Бакалавр, Магистр, Академик, Бог IT

**Comment by Nemec25** [comment]
Прочитать книгу, Курсы, Олимпиада, Школа, Училище, Университет, Магистратура, Академия

**Comment by Nesk27** [comment]
В знаниях го Училище, Колледж, Институт, Второе высшее

**Comment by Nesk27** [comment]
Нет, вместо Училища предлагаю сделать школу

**Comment by fks213** [comment]
Прочитать книгу
Пройти курс
Пройти курс по GitHub
Поучаствовать в олимпиаде
Прослушать вебинар
Пройти стажировку
Покурить форум
Взломать базу данных
