### ISSUE TITLE
Напоминание

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#13]
для тех кто не помнит как строить параметры у списков
<Имя>|<Деньги>|<Опыт>|<Здоровье>|<Скорость Здоровья>|<Голод>|<Скорость голода>|<Время Денег>*
* Имя нужно строить с учетом параметров прим. Работа (+<Сколько дает денег>/+<Сколько дает опыта>)
Деньги - этот параметр может быть + или - либо 0 в зависимости от того тратим мы деньги или зарабатываем
Опыт - ну тут либо + либо 0
Здоровье, Скорость Здоровья, Голод, Скорость голода - аналогично деньгам
Время Денег - параметр определяющий через сколько будут получены деньги и опыт за работу

**Comment by pashkin-sergey** [comment]
Будет сделано, капитан)

**Comment by Nesk27** [comment]
++
