### ISSUE TITLE
Создать базовый интерфейс

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#2]
Базовый интерфейс включает: Статус бары, отображающие значение атрибутов «Жизнь», «Настроение», «Сытость»; Основные вкладки: «Работа», «Еда», «Отдых».

**Comment by Nesk27** [comment]
![default](https://cloud.githubusercontent.com/assets/17343065/15709308/d53ef5fc-2825-11e6-82fb-aa4f2d386b0f.jpg)

**Comment by Nesk27** [comment]
У кого еще есть предложения? Кидайте, из общего замутим один крутой)

**Comment by pashkin-sergey** [comment]
![img_20160601_183448](https://cloud.githubusercontent.com/assets/17338614/15710174/93c8b388-282a-11e6-9c97-7baebbbdae06.jpg)

**Comment by fks213** [comment]
Не ну мастера заливать фото в правильной ориентации :+1:
