### ISSUE TITLE
Список "Работа"

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#3]
Создание списков действий по вкладкам. Распределение создания отдельной вкладки распределяется на каждого участника проекта.

**Comment by fks213** [comment]
Народ, предлагайте свои идеи по спискам, потом соберем один...

**Comment by pashkin-sergey** [comment]
личн. транспорт: велосипед, мопед, ока, субару, мерс

**Comment by fks213** [comment]
Предлагаю начать со вкладки Работа...

**Comment by ilyarebenok** [comment]
давайте без субару. на ней далеко не уедешь:)

**Comment by Nemec25** [comment]
Так, без Субары никак, ну просто будет много тратится денег на обслуживание))

**Comment by Nemec25** [comment]
Работа: промоутер, продавец в KFC, грузчик, продавец-консультант, системный администратор, junior-developer, тестировщик, хакер, developer, senior developer,  ФСБ-шник:)

**Comment by ilyarebenok** [comment]
Так то в KFC только с докторской берут. Так что до этой вышки дослужиться слажно)

**Comment by ilyarebenok** [comment]
А если серьёзно, то хакер как-то по-моему выбивается.

**Comment by Nesk27** [comment]
Нужен пункт Переустановщик винды :D

**Comment by fks213** [comment]
можно добавить главу IT отдела. Короче это превратиться в бред, создаю отдельные issue по каждой вкладке

**Comment by fks213** [comment]
Фрилансер, Глава IT компании, Преподаватель, Тыжпрограммист :D

**Comment by fks213** [comment]
промоутер
продавец в KFC
Переустановщик винды
системный администратор
junior-developer
тестировщик
Фрилансер
Тыжпрограммист
developer
TeamЛидка
ФСБ-шник
Глава IT компании

**Comment by Nemec25** [comment]
продавец в KFC
Переустановщик винды
системный администратор
junior-developer
тестировщик
Фрилансер
Тыжпрограммист
developer
TeamЛидка
ФСБ-шник
Глава IT компании
