### ISSUE TITLE
Разработать вкладки

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#4]
Без лишних слов, ваши предложения?

**Comment by fks213** [comment]
Предлагаю следующие вкладки: Работа, Отдых, Компьютер, Личный транспорт,  Курсы

**Comment by Nemec25** [comment]
Надо разделить работу на основную и дополнительную, сделаем разделение внутри вкладки или разобьём на две отдельные?

**Comment by Nemec25** [comment]
Идея про вкладки такова: Работа( внутри разделение на основную и дополнительную), Досуг, ПК, Покупки, Учёба( либо Знания).

**Comment by pashkin-sergey** [comment]
Предлагаю сделать "Банк", чтобы брать там деньги на некоторое время.

**Comment by ilyarebenok** [comment]
Про разделение вкладки "Работа " не согласен. Не думаю что нам надо нагромождение уже и так существующих вкладок.

**Comment by ilyarebenok** [comment]
Банк очень интересная идея но не думаю что мы успеем её реализовать. Лучше сконцентрироваться на уже разработанных вкладках.

**Comment by ilyarebenok** [comment]
Давайте уже как-то уже закончим с этим вопросом и определимся с финальной версией вкладок.

**Comment by fks213** [comment]
Утверждаем вкладки: Работа, Досуг, Компьютер, Транспорт, Курсы. Все согласны?

**Comment by ilyarebenok** [comment]
Я за!!!

**Comment by Nemec25** [comment]
Может всё-таки не Курсы, а иначе назовём данную вкладку? Я за название - Учёба.  И что насчёт вкладки Покупки?

**Comment by fks213** [comment]
Тогда уж не учёба, а Знания. Покупки в пень

**Comment by pashkin-sergey** [comment]
согласин

**Comment by Nesk27** [comment]
Считаю что покупки не нужны. Знания звучит хорошо.

**Comment by ilyarebenok** [comment]
ok

**Comment by fks213** [comment]
Так финал Работа, Досуг, Компьютер, Транспорт, Знания. Issue закрываю, делаем списки!
