### ISSUE TITLE
Разработать уровни сложности

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#5]
Основная концепция всем понятна, нужно детально проработать этот момент.

**Comment by Nemec25** [comment]
Считаю, что нужно сделать 3 уровня сложности, которые влияют на скорость игры, тем самым уменьшая или увеличивая время на принятие решения в процессе игры.

**Comment by Nemec25** [comment]
Считаю, что нужно сделать 3 уровня сложности, которые влияют на скорость игры, тем самым уменьшая или увеличивая время на принятие решения сделать какой-либо шаг  в процессе игры.

**Comment by fks213** [comment]
Предлагаю сделать два уровня сложности

**Comment by Nemec25** [comment]
Оставляем два уровня сложности: "Гуманитарий" и "Технарь"
