### ISSUE TITLE
Проработать стиль интерфейса

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#6]
Принимаются предложения по цветовой теме расположению элементов и прочему, желательно прилагать эскиз.

**Comment by ilyarebenok** [comment]
Кинул финальную версию) если всё ок то давайте закроем вопрос.

**Comment by ilyarebenok** [comment]
![0q2nwgvqbms](https://cloud.githubusercontent.com/assets/17649774/15790830/77530eac-29f5-11e6-9982-40e475f1dcdf.jpg)

**Comment by Nemec25** [comment]
Как общая концепция - сойдёт. Вопрос закрыт.
