### ISSUE TITLE
Настроить систему сборки

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#7]
Лично займусь этим вопросом, будет желание помочь отпишитесь.

**Comment by evgeny-p** [comment]
Возможно, подойдет этот сервис: https://www.appveyor.com/

**Comment by fks213** [comment]
Евгений Сергеевич @evgeny-p , а систему сборки можно фиктивную сделать?

**Comment by fks213** [comment]
Вопрос снят, батька зарешал)
