### ISSUE TITLE
Список "Досуг"

### ISSUE THREAD

**Issue by fks213** [is541-sibsutis/coder-simulator#9]

**Comment by Nemec25** [comment]
Сибгутка!!!:D

**Comment by fks213** [comment]
Спать, Дошик, Сибгутка, Семейный ужин, Кафе, Баня, Ресторан, Шведский стол, СПА, Курорт

**Comment by Nemec25** [comment]
Спать
Сьесть Доширак
Ребрышки
Кинотеатр
Кафе
Баня
Семейный ужин
Ресторан
СПА
Гольф
Курорт
